<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function brandsFromProvider(Provider $provider){
        return $this->getEntityManager()->createQuery(
            "SELECT partial p.{brand, id}
            FROM SruCoreBundle:Product p
            WHERE p.provider = :id")
            ->setParameter("id", $provider->getId())->getResult();
    }

    public function likeThisName($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e.name, e.id
            FROM SruCoreBundle:Brand e
            WHERE e.name LIKE :name
            ORDER BY e.name ASC")
            ->setParameter("name", "%".$name."%")->getResult();
    }
}
