<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function likeThisName($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e.name, e.id
            FROM SruCoreBundle:Category e
            WHERE e.name LIKE :name
            ORDER BY e.name ASC")
            ->setParameter("name", "%".$name."%")->getResult();
    }

    public function likeThisNameRestrict($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e
            FROM SruCoreBundle:Category e
            WHERE e.name LIKE :name
            ORDER BY e.name ASC")
            ->setParameter("name", "%".$name."%")->getResult();
    }


/*"SELECT p
            FROM SruCoreBundle:Product p
            JOIN p.picture pic
            WHERE (pic.name = :name)")->setParameter("name",$picture->getName())->getResult();*/

    public function categoriesFromProvider(Provider $provider){
        return $this->getEntityManager()->createQuery(
            "SELECT e
            FROM SruCoreBundle:Category e
            JOIN e.product pro
            WHERE pro.provider = :id")
            ->setParameter("id", $provider->getId())->getResult();
    }
}
