<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{

    public function picturesFromProvider(Provider $provider){
        return $this->getEntityManager()->createQuery(
            "SELECT e
            FROM SruCoreBundle:Picture e
            JOIN e.product pro
            WHERE pro.provider = :id")
            ->setParameter("id", $provider->getId())->getResult();
    }
}
