<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends EntityRepository
{
    public function likeThisName($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e.libelle, e.id
            FROM SruCoreBundle:Profil e
            WHERE e.libelle LIKE :libelle
            ORDER BY e.libelle ASC")
            ->setParameter("libelle", "%".$name."%")->getResult();
    }
}
