<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    public function likeThisCode($code){
        return $this->getEntityManager()->createQuery(
            "SELECT e.code, e.id
            FROM SruCoreBundle:Promotion e
            WHERE e.code LIKE :code
            ORDER BY e.code ASC")
            ->setParameter("code", "%".$code."%")->getResult();
    }
}
