<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentZoneRepository extends EntityRepository
{

    public function likeThisName($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e.zone, e.id
            FROM SruCoreBundle:ShipmentZone e
            WHERE e.zone LIKE :zone
            ORDER BY e.zone ASC")
            ->setParameter("zone", "%".$name."%")->getResult();
    }
}
