<?php

namespace Sru\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function likeThisName($name){
        return $this->getEntityManager()->createQuery(
            "SELECT e.username,e.email, e.id
            FROM SruCoreBundle:User e
            WHERE e.username LIKE :name OR e.email LIKE :name
            ORDER BY e.username ASC")
            ->setParameter("name", "%".$name."%")->getResult();
    }
}
